/*
 * This file is part of SQL Workbench/J, https://www.sql-workbench.eu
 *
 * Copyright 2002-2020 Thomas Kellerer.
 *
 * Licensed under a modified Apache License, Version 2.0 (the "License")
 * that restricts the use for certain governments.
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.sql-workbench.eu/manual/license.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * To contact the author please send an email to: support@sql-workbench.eu
 */
package workbench.gui.components;

import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;

import javax.swing.JDialog;

import workbench.resource.ResourceMgr;
import workbench.resource.Settings;

import workbench.gui.WbSwingUtilities;
import workbench.gui.actions.EscAction;

/**
 *
 * @author Thomas Kellerer
 */
public class MasterPasswordDialog
  extends JDialog
  implements ActionListener
{
  private boolean cancelled = false;
  private boolean removeMasterPwd = false;
  private EscAction escAction;
  
  public MasterPasswordDialog(Dialog parent)
  {
    super(parent, ResourceMgr.getString("TxtWindowTitleMasterPwd"), true);
    escAction = new EscAction(this, this);

    setResizable(true);
    initComponents();
    if (!Settings.getInstance().getUseMasterPassword())
    {
      removePwdButton.setVisible(false);
    }
  }

  public boolean doRemoveMasterPassword()
  {
    return removeMasterPwd;
  }

  public boolean wasCancelled()
  {
    return cancelled;
  }

  public String getMasterPassword()
  {
    if (removeMasterPwd) return null;
    return pwdInput.getText();
  }

  @Override
  public void actionPerformed(ActionEvent e)
  {
    if (e.getSource() == escAction)
    {
      doCancel();
    }
  }

  private void doCancel()
  {
    this.removeMasterPwd = false;
    this.cancelled = true;
    closeWindow();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    oldPwdLabel = new javax.swing.JLabel();
    newPwdLabel = new javax.swing.JLabel();
    pwdInput = new javax.swing.JPasswordField();
    repeatPwd = new javax.swing.JPasswordField();
    jPanel1 = new javax.swing.JPanel();
    removePwdButton = new javax.swing.JButton();
    okButton = new WbButton();
    cancelButton = new WbButton();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    getContentPane().setLayout(new java.awt.GridBagLayout());

    oldPwdLabel.setText(ResourceMgr.getString("LblNewPwd")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(13, 12, 8, 0);
    getContentPane().add(oldPwdLabel, gridBagConstraints);

    newPwdLabel.setText(ResourceMgr.getString("LblPwdRepeat")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(0, 12, 8, 0);
    getContentPane().add(newPwdLabel, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(13, 8, 8, 12);
    getContentPane().add(pwdInput, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(0, 8, 8, 12);
    getContentPane().add(repeatPwd, gridBagConstraints);

    jPanel1.setLayout(new java.awt.GridBagLayout());

    removePwdButton.setText("Remove");
    removePwdButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        removePwdButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.weightx = 1.0;
    jPanel1.add(removePwdButton, gridBagConstraints);

    okButton.setText(ResourceMgr.getString("LblOK")); // NOI18N
    okButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        okButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    jPanel1.add(okButton, gridBagConstraints);

    cancelButton.setText(ResourceMgr.getString("LblCancel")); // NOI18N
    cancelButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        cancelButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
    jPanel1.add(cancelButton, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.weightx = 1.0;
    jPanel1.add(jPanel2, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(19, 12, 16, 12);
    getContentPane().add(jPanel1, gridBagConstraints);

    jLabel1.setText(ResourceMgr.getString("LblMasterPwdWarn")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(5, 12, 0, 12);
    getContentPane().add(jLabel1, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
  {//GEN-HEADEREND:event_cancelButtonActionPerformed
    doCancel();
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
  {//GEN-HEADEREND:event_okButtonActionPerformed
    char[] pwd = pwdInput.getPassword();
    if (pwd == null || pwd.length == 0)
    {
      WbSwingUtilities.showErrorMessage("No password specified!");
      return;
    }
    if (!Arrays.equals(pwdInput.getPassword(), repeatPwd.getPassword()))
    {
      WbSwingUtilities.showErrorMessage("The passwords do not match!");
      return;
    }
    this.removeMasterPwd = false;
    this.cancelled = false;
    closeWindow();
  }//GEN-LAST:event_okButtonActionPerformed

  private void removePwdButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_removePwdButtonActionPerformed
  {//GEN-HEADEREND:event_removePwdButtonActionPerformed
    this.removeMasterPwd = true;
    this.cancelled = false;
    closeWindow();
  }//GEN-LAST:event_removePwdButtonActionPerformed

  private void closeWindow()
  {
    this.dispose();
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JLabel newPwdLabel;
  private javax.swing.JButton okButton;
  private javax.swing.JLabel oldPwdLabel;
  private javax.swing.JPasswordField pwdInput;
  private javax.swing.JButton removePwdButton;
  private javax.swing.JPasswordField repeatPwd;
  // End of variables declaration//GEN-END:variables
}
