/*
 * This file is part of SQL Workbench/J, https://www.sql-workbench.eu
 *
 * Copyright 2002-2021, Thomas Kellerer
 *
 * Licensed under a modified Apache License, Version 2.0
 * that restricts the use for certain governments.
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at.
 *
 *     https://www.sql-workbench.eu/manual/license.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * To contact the author please send an email to: support@sql-workbench.eu
 *
 */
package workbench.gui.settings;

import javax.swing.JPanel;

import workbench.interfaces.Restoreable;
import workbench.resource.ResourceMgr;

import workbench.gui.components.StringPropertyEditor;
import workbench.gui.components.TextComponentMouseListener;
import workbench.gui.filetree.FileTreeSettings;

/**
 *
 * @author  Thomas Kellerer
 */
public class FileTreeOptionsPanel
  extends JPanel
  implements Restoreable
{
  public FileTreeOptionsPanel()
  {
    super();
    initComponents();
  }


  @Override
  public void restoreSettings()
  {
    this.excludedExtensions.setText(FileTreeSettings.getExcludedExtensions());
    this.excludedFiles.setText(FileTreeSettings.getExcludedFiles());
  }

  @Override
  public void saveSettings()
  {
    FileTreeSettings.setExcludedExtensions(excludedExtensions.getText());
    FileTreeSettings.setExcludedFiles(excludedFiles.getText());
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    namesLabel = new javax.swing.JLabel();
    excludedFiles = new StringPropertyEditor();
    excludedExtensions = new StringPropertyEditor();
    extensionsLabel = new javax.swing.JLabel();

    setLayout(new java.awt.GridBagLayout());

    namesLabel.setLabelFor(excludedFiles);
    namesLabel.setText(ResourceMgr.getString("LblFileTreeExclFiles")); // NOI18N
    namesLabel.setToolTipText(ResourceMgr.getString("d_LblFileTreeExclFiles")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    add(namesLabel, gridBagConstraints);

    excludedFiles.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    excludedFiles.setToolTipText(ResourceMgr.getString("d_LblFileTreeExclFiles")); // NOI18N
    excludedFiles.setName("name"); // NOI18N
    excludedFiles.addMouseListener(new TextComponentMouseListener());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(1, 8, 0, 3);
    add(excludedFiles, gridBagConstraints);

    excludedExtensions.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    excludedExtensions.setToolTipText(ResourceMgr.getString("d_LblFileTreeExclExts")); // NOI18N
    excludedExtensions.setName("excludedExtensions"); // NOI18N
    excludedFiles.addMouseListener(new TextComponentMouseListener());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(5, 8, 6, 3);
    add(excludedExtensions, gridBagConstraints);

    extensionsLabel.setLabelFor(extensionsLabel);
    extensionsLabel.setText(ResourceMgr.getString("LblFileTreeExclExts")); // NOI18N
    extensionsLabel.setToolTipText(ResourceMgr.getString("d_LblFileTreeExclExts")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
    add(extensionsLabel, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JTextField excludedExtensions;
  public javax.swing.JTextField excludedFiles;
  public javax.swing.JLabel extensionsLabel;
  public javax.swing.JLabel namesLabel;
  // End of variables declaration//GEN-END:variables


}
